name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['8.x']
        node-version: ['18.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore .NET dependencies
        run: dotnet restore StockMarketDashboard.API/StockMarketDashboard.sln

      - name: Build .NET project
        run: dotnet build StockMarketDashboard.API/StockMarketDashboard.sln --configuration Release

      - name: Publish .NET project
        run: dotnet publish StockMarketDashboard.API/StockMarketDashboard.sln -c Release -o ./api_publish

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Angular dependencies
        run: |
          cd StockMarketDashboard/StockMarketDashboard-FrontEnd
          npm install

      - name: Build Angular project
        run: |
          cd StockMarketDashboard/StockMarketDashboard-FrontEnd
          npm run build -- --configuration production
        env:
          CI: ''

      - name: Prepare deployment structure
        run: |
          mkdir -p ./deployment/frontend
          mkdir -p ./deployment/api
          cp -r api_publish/* ./deployment/api
          cp -r StockMarketDashboard/StockMarketDashboard-FrontEnd/dist/stock-market-dashboard-front-end/* ./deployment/frontend
          cp nginx.conf ./deployment/nginx.conf

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'StockMarketDashboardAPI'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: './deployment'
