name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job for deploying the API
  deploy-api:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['8.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore .NET dependencies
        run: dotnet restore StockMarketDashboard.API/StockMarketDashboard.sln

      - name: Build .NET project
        run: dotnet build StockMarketDashboard.API/StockMarketDashboard.sln --configuration Release

      - name: Publish .NET project
        run: dotnet publish StockMarketDashboard.API/StockMarketDashboard.sln -c Release -o ./api_publish

      - name: Deploy .NET API to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'StockMarketDashboardAPI'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API }}
          package: './api_publish'

  # Job for deploying the Angular Frontend
  deploy-frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Angular dependencies
        run: |
          cd StockMarketDashboard-FrontEnd
          npm install

      - name: Build Angular project
        run: |
          cd StockMarketDashboard-FrontEnd
          npm run build -- --configuration production

      - name: Deploy Angular Frontend to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'StockMarketDashboard'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
          package: './dist/stock-market-dashboard-front-end/browser'
